# Generated by Django 4.2.11 on 2024-06-06 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='b_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RK', models.IntegerField()),
                ('RN', models.CharField(max_length=255)),
                ('Marka', models.CharField(max_length=255)),
                ('Model', models.CharField(max_length=255)),
                ('G_PR', models.IntegerField()),
                ('KM', models.IntegerField()),
                ('Kupe', models.CharField(max_length=255)),
                ('Rama', models.CharField(max_length=255)),
                ('Dvigatel', models.CharField(max_length=255)),
                ('Descr', models.TextField()),
                ('Problema', models.TextField()),
                ('R_DATA', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='c_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RK', models.IntegerField()),
                ('ime', models.CharField(max_length=255)),
                ('telefon', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='w_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RK', models.IntegerField()),
                ('W_ID', models.IntegerField()),
                ('WORK', models.TextField()),
                ('PRICE', models.IntegerField()),
            ],
        ),
    ]
