# Generated by Django 4.2.13 on 2024-06-13 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='b_data',
            name='R_DATA',
            field=models.DateField(blank=True, db_column='R_DATA', null=True),
        ),
    ]
