# Generated by Django 4.2.13 on 2024-06-09 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_b_data_id_c_data_id_p_data_id_w_data_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='b_data',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='c_data',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='p_data',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='w_data',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
